language: python

python:
  - "2.7"
#  - "3.3"
#  - "3.4"

install:
  - which python
  - which pip

before_script:
  - export PYTHONPATH="src:test:$PYTHONPATH"

script:
  - cd test
  - python -u framaAnalyzerTest.py
