language: python

python:
  - "2.7"

install:
  - which python
  - which pip

before_script:
  - export PYTHONPATH="./src:./test:$PYTHONPATH"

script:
  - echo $PYTHONPATH
  - pwd
  - ls
  - python -u ./test/framaAnalyzerTest.py
