language: python

python:
  - "2.7"
#  - "3.3"
#  - "3.4"

install:
  - which python
  - which pip

after_install:
  - export PYTHONPATH="src:test:$PYTHONPATH"

script:
  - python -u test/framaAnalyzerTest.py
  - cd test/ && behave
  - cd ..
  # Run py.test with 'v' (verbose) to show test function names and  
  # 'rs' to show reasons for skipped tests
  - py.test -v -rs test