language: python

python:
  - "2.7"
#  - "3.3"
#  - "3.4"

install:
  - which python
  - which pip
  - which py.test
  - py.test --version

script:
  - python -v -m unittest discover -s test -p "*Test.py"
  - cd test/ && behave
  - cd ..
  # Run py.test with 'v' (verbose) to show test function names and  
  # 'rs' to show reasons for skipped tests
  - py.test -v -rs test